# Generated by Django 2.0.4 on 2018-07-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180728_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='time_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='time_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
