# Generated by Django 2.0.4 on 2018-08-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180728_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecard',
            name='time_ended',
        ),
        migrations.RemoveField(
            model_name='timecard',
            name='time_started',
        ),
        migrations.AddField(
            model_name='timecard',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timecard',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
    ]
