# Generated by Django 2.0.4 on 2018-08-03 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180802_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timecard',
            old_name='date_ended',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='timecard',
            name='date_started',
        ),
    ]
