# Generated by Django 2.0.4 on 2018-08-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180802_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecard',
            name='funded',
            field=models.BooleanField(default=False),
        ),
    ]
