# Generated by Django 2.0.4 on 2018-08-08 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_timecard_funded'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimecardSummary',
            fields=[
            ],
            options={
                'verbose_name': 'timecard summary',
                'verbose_name_plural': 'timecard summaries',
                'proxy': True,
                'indexes': [],
            },
            bases=('accounts.timecard',),
        ),
    ]
